model:
  params:
    tokenizer_config:
      target: transformers.AutoTokenizer
      instance_name: 'tokenizer'
      from_pretrained: "black-forest-labs/FLUX.1-dev"
      params:
        subfolder: "tokenizer_2"

    encoder_config:
      target: core.face_t5.face_t5.FaceT5Encoder
      instance_name: 'encoder'
      trainable: false
      params:
        precision: torch.bfloat16
        face_model_path: ""
